# CS181_P1

In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

## Data Preprocessing
### 1. Read in raw data
- train.csv.gz -> df_train_0
- test.csv.gz -> df_test_0

In [2]:
###############################################
#            Data Preprocessing               #
###############################################

## 1. Read in raw data
# use panda to read in data 
df_train_0 = pd.read_csv("../train.csv.gz")
df_test_0 = pd.read_csv("../test.csv.gz")

In [3]:
# view the train data
#df_train_0.head()

,smiles,feat_001,feat_002,feat_003,feat_004,feat_005,feat_006,feat_007,feat_008,feat_009,...,feat_248,feat_249,feat_250,feat_251,feat_252,feat_253,feat_254,feat_255,feat_256,gap
0,c1ccc(o1)-c1ccc(s1)-c1cnc(-c2scc3[se]ccc23)c2n...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.19
1,C1=CC=C(C1)c1cc2ncc3c4[SiH2]C=Cc4ncc3c2c2=C[Si...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.60
2,[nH]1c-2c([SiH2]c3cc(-c4scc5C=CCc45)c4nsnc4c-2...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.49
3,[nH]1c2-c3occc3Cc2c2c1cc(-c1cccc3=C[SiH2]C=c13...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.36
4,c1cnc2c3oc4cc(-c5ncncn5)c5nsnc5c4c3c3cocc3c2c1,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.98

In [5]:
# view the test data
#df_test_0.head()

,Id,smiles,feat_001,feat_002,feat_003,feat_004,feat_005,feat_006,feat_007,feat_008,...,feat_247,feat_248,feat_249,feat_250,feat_251,feat_252,feat_253,feat_254,feat_255,feat_256
0,1,c1sc(-c2cnc3c(c2)c2nsnc2c2cc4cccnc4cc32)c2cc[n...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,[nH]1cccc1-c1cc2c3nsnc3c3c4sccc4[nH]c3c2s1,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,[nH]1c2cc(-c3ccc[se]3)c3nsnc3c2c2c3cscc3c3ccc4...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,[nH]1c(cc2cnc3c(c12)c1=C[SiH2]C=c1c1ccc2=CCC=c...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,c1sc(-c2sc(-c3sc(-c4scc5[se]ccc45)c4ccoc34)c3c...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 2. clean data

In [10]:
## 2. Clean data
# 2.1 combine train and test for easier feature engineering
# (1) delete 'Id' column
df_test = df_test_0.drop(['Id'], axis=1)
# (2) delete 'gap' column
df_train = df_train_0.drop(['gap'], axis=1)
# (3) combine train and test
df_all = pd.concat((df_train, df_test), axis=0)

# 2.2 Drop the 'smiles' column
df_all = df_all.drop(['smiles'], axis=1)

In [11]:
# view the cleaned data
#df_all.head()

,feat_001,feat_002,feat_003,feat_004,feat_005,feat_006,feat_007,feat_008,feat_009,feat_010,...,feat_247,feat_248,feat_249,feat_250,feat_251,feat_252,feat_253,feat_254,feat_255,feat_256
0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 3. specify x and y

In [12]:
# Specify x and y
# 3.1 specify gap values as y
Y_train = df_train_0.gap.values

# 3.2 specify x values
# index of row where testing examples start
test_idx = df_train.shape[0]
# split x_train and x_test
X_train = df_all.values[:test_idx]
X_test = df_all.values[test_idx:]

# 3.3 view data structure
print("Train features:", X_train.shape)
print("Train gap:", Y_train.shape)
print("Test features:", X_test.shape)

Train features: (1000000, 256)
Train gap: (1000000,)
Test features: (824230, 256)

## Feature Selection
Use baseline model to select impotant features
- Linear Regression: drop coef=0
- Random Forest: drop importance=0

### 1. Fit base line models

In [17]:
###############################################
#             Feature Selection               #
###############################################
# Use baseline model to select impotant features
# 1. Fit base line models
# 1.1 Fit Linear Regressoin
LR = LinearRegression()
LR.fit(X_train, Y_train)
#LR_pred = LR.predict(X_test)

# 1.2 Fit Random Forest
RF = RandomForestRegressor()
RF.fit(X_train, Y_train)
#RF_pred = RF.predict(X_test)

# 1.3 Calculate initial R^2
print("R^2 for Linear Regression is: ",LR.score(X_train, Y_train))
print("R^2 for Random Forest is: ",RF.score(X_train, Y_train))

R^2 for Linear Regression is:  0.460972905391
R^2 for Random Forest is:  0.554153429521

### 2. Drop vaccant predictors

In [22]:
# 2. Drop predictors that are unimportant in both LR and RF
LR_coef = LR.coef_
RF_imp = RF.feature_importances_
i0 = (LR_coef == 0) & (RF_imp == 0)
X_train1 = X_train[:,i0 == False]
X_test1 = X_test[:,i0 == False]
# view data structure after drop
print("Train features after 1 drop:", X_train1.shape)
print("Train gap:", Y_train.shape)
print("Test features after 1 drop:", X_test1.shape)

Train features after 1 drop: (1000000, 58)
Train gap: (1000000,)
Test features after 1 drop: (824230, 58)

### 3. Refit baseline models

In [20]:
# 3. Refit base line models
# 3.1 Refit Linear Regressoin
LR1 = LinearRegression()
LR1.fit(X_train1, Y_train)

# 3.2 Refit Random Forest
RF1 = RandomForestRegressor()
RF1.fit(X_train1, Y_train)

# 3.3 Recalculate R^2
#print(LR1.score(X_train1, Y_train))
#print(RF1.score(X_train1, Y_train))
print("R^2 for refitted Linear Regression is: ",LR1.score(X_train1, Y_train))
print("R^2 for refitted Random Forest is: ",RF1.score(X_train1, Y_train))

R^2 for refitted Linear Regression is:  0.460990413087
R^2 for refitted Random Forest is:  0.554155440928

### 4. Drop features < 0

In [21]:
# 4.1 Dop features with RF importance < 0
RF_imp1 = RF1.feature_importances_
LR_coef1 = LR.coef_
i1 = (RF_imp1 > 0)
X_train2 = X_train1[:,i1]
X_test2 = X_test1[:,i1]

In [23]:
# 4.2 view data structure
print("Train features after 2 drops:", X_train2.shape)
print("Train gap:", Y_train.shape)
print("Test features after 2 drops:", X_test2.shape)

Train features after 2 drops: (1000000, 31)
Train gap: (1000000,)
Test features after 2 drops: (824230, 31)

## Generate Prediciton on Test

In [ ]:
# function to generate prediciton on test set
def write_to_file(filename, predictions):
    with open(filename, "w") as f:
        f.write("Id,Prediction\n")
        for i,p in enumerate(predictions):
            f.write(str(i+1) + "," + str(p) + "\n")

In [ ]:
#write_to_file("sample1.csv", LR_pred)
#write_to_file("sample2.csv", RF_pred)